server:
  port: 1112
eureka:
  instance:
    hostname: eureka2
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://eureka1:1111/eureka/