server:
  port: 1112
eureka:
  instance:
    hostname: peer2
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://peer1:1111/eureka/